-- Use the below drop statements to reset the database to default have data.
DROP TABLE IF EXISTS LIBRARY_BOOK_TRANSACTIONS;
DROP TABLE IF EXISTS LIBRARY_BOOK;
DROP TABLE IF EXISTS LIBRARY_MEMBER;

-- To create LIBRARY_BOOK table: Stores books details.
CREATE TABLE IF NOT EXISTS LIBRARY_BOOK 
	(	ENTRY_ID IDENTITY NOT NULL,
		PRICE DOUBLE,
		BOOK_ID VARCHAR(50) NOT NULL,
		BOOK_NAME VARCHAR(50),
		BOOK_TYPE VARCHAR(150),
		AUTHOR VARCHAR(50),
		ISBN_CODE VARCHAR(50),
		BOOK_STATUS VARCHAR(50) NOT NULL,
		DATE_OF_ENTRY VARCHAR(50) NOT NULL,
		PUBLISHED_ON VARCHAR(50),
		MEMBER_ID INT,
		
		PRIMARY KEY (ENTRY_ID)
	);
	
-- To create LIBRARY_MEMBER table:	Stores Member informations. 	 
CREATE TABLE IF NOT EXISTS LIBRARY_MEMBER 
	(	MEMBER_ID IDENTITY NOT NULL,
		NAME VARCHAR(50),
		CONTACT VARCHAR(50),
		ADDRESS VARCHAR(50),
		EXPIRATION_DATE_OF_MEMBERSHIP VARCHAR(50) NOT NULL,
		START_DATE_OF_MEMBERSHIP VARCHAR(50) NOT NULL,
		MEMBER_STATUS VARCHAR(50) NOT NULL,
		NUMBER_OF_BOOK_ISSUED INT,
		
		PRIMARY KEY (MEMBER_ID)
	);

-- To create LIBRARY_BOOK_TRANSACTIONS table:	Stores all library book transactions. 	
CREATE TABLE IF NOT EXISTS LIBRARY_BOOK_TRANSACTIONS
	(	TRANSACTION_ID IDENTITY NOT NULL,
		BOOK_ID VARCHAR(50) NOT NULL,
		BOOK_NAME VARCHAR(50),
		ISSUED_ON TIMESTAMP WITH TIME ZONE NOT NULL,
		RETURNED_ON TIMESTAMP WITH TIME ZONE,
		TRANSACTION_STATUS VARCHAR(50) NOT NULL,
		FK2_LIBRARY_BOOK_ENTRYID INT,
	 	FK2_LIBRARY_MEMBER_MEMBERID INT,
		
		FOREIGN KEY (FK2_LIBRARY_BOOK_ENTRYID) REFERENCES LIBRARY_BOOK(ENTRY_ID),
		FOREIGN KEY (FK2_LIBRARY_MEMBER_MEMBERID) REFERENCES LIBRARY_MEMBER(MEMBER_ID)
	);